#!/bin/sh
# IFS means internal field separator, this determines what counts as a separate entry
# to iterate over in the loop below
IFS=$(printf '\n\t')
for i in $(task scheduled:today status:pending export | jq '.[].description' --raw-output); do
    printf -- "- [ ] %s\n" "$i"
done
